{
  "_annotation": {
    "cve_id": "CVE-2024-56374",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-56374.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "2D4D5856-1C82-51BB-8F49-EC80A4A5AF03",
                "versionEndExcluding": "4.2.18",
                "versionStartIncluding": "4.2",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "E56ED194-C3A3-5992-BE47-0A0DD281CB98",
                "versionEndExcluding": "5.0.11",
                "versionStartIncluding": "5.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "8F8E448E-418D-5C0A-A164-B01447BD5979",
                "versionEndExcluding": "5.1.5",
                "versionStartIncluding": "5.1",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}