{
  "_annotation": {
    "cve_id": "CVE-2024-35225",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-35225.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:jupyter:jupyter_server_proxy:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "85426D34-5EE4-5D45-9F58-F81B8FE541AC",
                "versionEndExcluding": "3.2.4",
                "versionStartIncluding": "3.0.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:jupyter:jupyter_server_proxy:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "25690C07-C189-5829-90AB-B24AABBE04F0",
                "versionEndExcluding": "4.2.0",
                "versionStartIncluding": "4.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}