{
  "_annotation": {
    "cve_id": "CVE-2024-36404",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-36404.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:geotools:geotools:*:*:*:*:*:maven:*:*",
                "matchCriteriaId": "6C0C96BE-CB8B-51F7-98E7-03690EE354B2",
                "versionEndExcluding": "29.6",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:geotools:geotools:*:*:*:*:*:maven:*:*",
                "matchCriteriaId": "EE4FF43A-ED7C-5762-9AFB-231A5E4AD39C",
                "versionEndExcluding": "30.4",
                "versionStartIncluding": "30.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:geotools:geotools:*:*:*:*:*:maven:*:*",
                "matchCriteriaId": "411C8988-1875-53F5-ACB6-2F05CC1FD1B1",
                "versionEndExcluding": "31.2",
                "versionStartIncluding": "31.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}