{
  "_annotation": {
    "cna": "hackerone",
    "cve_id": "CVE-2024-37400",
    "description": "An out of bounds read in Ivanti Connect Secure before version 22.7R2.3 allows a remote unauthenticated attacker to trigger an infinite loop, causing a denial of service.",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-37400.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://forums.ivanti.com/s/article/Security-Advisory-Ivanti-Connect-Secure-ICS-Ivanti-Policy-Secure-IPS-Ivanti-Secure-Access-Client-ISAC-Multiple-CVEs"
    ]
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:ivanti:connect_secure:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "0B38BA0F-E430-5480-8005-996482695554",
                "versionEndExcluding": "22.7r2.3",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}