{
  "_annotation": {
    "cve_id": "CVE-2024-53908",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-53908.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "F2319EFF-95F0-5BF9-A39D-9D672D929597",
                "versionEndExcluding": "5.1.4",
                "versionStartIncluding": "5.1",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "E8ADE681-7F29-5E32-AF2C-C18178AB66D8",
                "versionEndExcluding": "5.0.10",
                "versionStartIncluding": "5.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "1D0E5BF8-413B-593D-A42E-FA160D925ED0",
                "versionEndExcluding": "4.2.17",
                "versionStartIncluding": "4.2",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}