{
  "_annotation": {
    "cna": "github_m",
    "cve_id": "CVE-2024-38355",
    "description": "Socket.IO is an open source, real-time, bidirectional, event-based, communication framework. A specially crafted Socket.IO packet can trigger an uncaught exception on the Socket.IO server, thus killing the Node.js process. This issue is fixed by commit `15af22fc22` which has been included in `socket.io@4.6.2` (released in May 2023). The fix was backported in the 2.x branch as well with commit `d30630ba10`. Users are advised to upgrade. Users unable to upgrade may attach a listener for the \"error\" event to catch these errors.",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-38355.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/socketio/socket.io/commit/15af22fc22bc6030fcead322c106f07640336115",
      "https://github.com/socketio/socket.io/commit/d30630ba10562bf987f4d2b42440fc41a828119c",
      "https://github.com/socketio/socket.io/security/advisories/GHSA-25hc-qcg6-38wj"
    ]
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:socket:socket.io:*:*:*:*:*:node.js:*:*",
                "matchCriteriaId": "542E6B1F-3A2F-5F29-B1BD-20D741FBD565",
                "versionEndExcluding": "2.5.1",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:socket:socket.io:*:*:*:*:*:node.js:*:*",
                "matchCriteriaId": "78D05F36-821A-5A74-9E8E-687187DE8CA2",
                "versionEndExcluding": "4.6.2",
                "versionStartIncluding": "3.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}