{
  "_annotation": {
    "cve_id": "CVE-2024-6923",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-6923.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "09F07DCA-6086-5305-98EA-8EC2A0A31B37",
                "versionEndIncluding": "3.13.0rc2",
                "versionStartIncluding": "3.13.0a1",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "DCAB51E1-A0D1-5DD3-B744-9AB8A40FBDE2",
                "versionEndExcluding": "3.12.5",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}