{
  "_annotation": {
    "cve_id": "CVE-2024-26130",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-26130.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:cryptography.io:cryptography:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "BDAE857E-8C66-4574-88CD-615D866340CA",
                "versionEndExcluding": "42.0.4",
                "versionStartIncluding": "38.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:cryptography_project:cryptography:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "3EDF6DE1-AE78-5E43-9FFF-41F00C7079D0",
                "versionEndExcluding": "42.0.4",
                "versionStartIncluding": "38.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:python-cryptography_project:python-cryptography:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "9555AA95-9578-513B-B5C5-DD529CE4726D",
                "versionEndExcluding": "42.0.4",
                "versionStartIncluding": "38.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}