{
  "_annotation": {
    "cve_id": "CVE-2024-4030",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-4030.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "3005A594-3F99-564F-AC81-786CB2E974C8",
                "versionEndExcluding": "3.13.0b1",
                "versionStartIncluding": "3.13.0a1",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "B2E4B428-578A-5ADB-A7FB-E3055BFC6587",
                "versionEndExcluding": "3.12.4",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}