{
  "_annotation": {
    "cve_id": "CVE-2025-26623",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-26623.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:exiv2:exiv2:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "341D074A-7184-53B6-9015-F7E9F972F6AA",
                "versionEndExcluding": "0.28.5",
                "versionStartIncluding": "0.28.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}