{
  "_annotation": {
    "cve_id": "CVE-2025-48956",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-48956.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:vllm-project:vllm:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "A456E72C-D8F3-5D84-AF49-9219A220D89F",
                "versionEndExcluding": "0.10.1.1",
                "versionStartIncluding": "0.1.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}