{
  "_annotation": {
    "cve_id": "CVE-2025-52898",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-52898.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:frappe:frappe:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "9434ED5D-A5D6-5DAE-8D79-32E81069E7D2",
                "versionEndExcluding": "15.58.0",
                "versionStartIncluding": "15.0.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:frappe:frappe:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "15E50C81-2142-5A82-808A-F568419042C0",
                "versionEndExcluding": "14.94.3",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}