{
  "_annotation": {
    "cve_id": "CVE-2025-21548",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-21548.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:oracle:mysql_connector\\/python:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "8373029C-EE96-5401-A88C-C0739EA6361F",
                "versionEndExcluding": "9.2.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:oracle:mysql_connectors:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "E77594E1-4C70-5DE9-B403-F85CE491B987",
                "versionEndExcluding": "9.2.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}