{
  "_annotation": {
    "cve_id": "CVE-2025-52896",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-52896.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:frappe:frappe:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "E5B2B33E-162A-53A3-B000-FDD67D390DF4",
                "versionEndExcluding": "15.57.0",
                "versionStartIncluding": "15.0.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:frappe:frappe:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "662C16FA-D3F3-551E-8280-6FE03C22856B",
                "versionEndExcluding": "14.94.2",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}