{
  "_annotation": {
    "cve_id": "CVE-2025-50182",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-50182.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:python:urllib3:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "FDE53700-B027-5679-8FBE-A45DEEECB470",
                "versionEndExcluding": "2.5.0",
                "versionStartIncluding": "2.2.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}