{
  "_annotation": {
    "cve_id": "CVE-2025-46722",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-46722.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:vllm-project:vllm:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "21577237-6DCC-5C31-966A-2359742BBAC6",
                "versionEndExcluding": "0.9.0",
                "versionStartIncluding": "0.7.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:vllm:vllm:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "43960D5B-51FB-5D69-A063-9D91F5484AC2",
                "versionEndExcluding": "0.9.0",
                "versionStartIncluding": "0.7.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}