{
  "_annotation": {
    "cve_id": "CVE-2025-54140",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-54140.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:pyload:pyload:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "5D6EE56E-8536-56AC-9957-91F7A11D6D90",
                "versionEndExcluding": "0.5.0b3.dev90",
                "versionStartIncluding": "0.5.0b3.dev89",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}