{
  "_annotation": {
    "cve_id": "CVE-2025-30355",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-30355.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:element-hq:synapse:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "2BCB90F7-8E3A-5BB7-BCE5-838520C5CF09",
                "versionEndExcluding": "1.127.1",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:matrix:synapse:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "91110619-0812-54E0-ACEE-BDD3CA05A419",
                "versionEndExcluding": "1.127.1",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}