{
  "_annotation": {
    "cve_id": "CVE-2025-53073",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-53073.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:sentry:sentry:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "B39E18A5-55E2-568F-A686-9C71E277F01C",
                "versionEndIncluding": "25.5.1",
                "versionStartIncluding": "25.1.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}